// <auto-generated />
namespace SysPharm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddTipoUsuarioInUsuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTipoUsuarioInUsuario));
        
        string IMigrationMetadata.Id
        {
            get { return "202106292331008_AddTipoUsuarioInUsuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
